### ISSUE TITLE
[Bug]: Problems with checkbox inputs

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#207] opened 2023-05-31 15:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

These inputs are optional, but I am forced to select an option here:
![image](https://github.com/russellbanks/Komac/assets/56180050/46b617bc-cc53-4425-abfd-aece6025eda9)

This one seems to be fine, but hitting confirm without selecting anything unexpectedly crashes Komac:
![image](https://github.com/russellbanks/Komac/assets/56180050/0841d44c-0f73-418f-9203-f88564019212)

**Comment by russellbanks** [comment] 2023-05-31 18:41
Thanks for reporting! This is a duplicate of #202 and was fixed in https://github.com/russellbanks/Komac/commit/74a3342b4e926152024a418667e73d3836d1082c, which will be in Komac 1.7.0 :)

If a prompt returns null, it's meant to signal Ctrl+C being pressed. If no checkboxes are checked, this was returning null rather than an empty list.

**Closed by russellbanks** 2023-05-31 18:41 UTC
Labels: bug, help wanted

**Comment by sitiom** [comment] 2023-05-31 23:26
> In terms of those two menus being 'optional', they have a default value so that you can just press enter. It's optional in the sense of not having to think about it.

Not too sure. I shouldn't be putting an installer scope, especially when it's a portable program. I had to manually remove the field after submitting the PR.
