### ISSUE TITLE
[Bug]: Komac is not correctly updating metadata

### ISSUE THREAD

**Issue by mdanish-kh** [russellbanks/Komac#250] opened 2023-07-14 20:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Noticed this in https://github.com/microsoft/winget-pkgs/pull/111683 and https://github.com/microsoft/winget-pkgs/pull/112103 where the ProductCodes were incorrect. 
In https://github.com/microsoft/winget-pkgs/pull/111781 and https://github.com/microsoft/winget-pkgs/pull/111765/files I noticed the InstallerUrls were incorrect.

No way to check if the manifest was manually tampered with later, but it doesn't seem to be the case.

**Comment by CoolPlayLin** [comment] 2023-07-15 00:38
Relate to #243 #215 #245

**Comment by russellbanks** [comment] 2023-07-19 19:34
The installer URLs matching issue was fixed in 1.9.0 and there will be patches if there are any edge cases.

For the product codes, there is a different method of retrieving them on non-Windows platform due to not being able to access `msi.dll`. I've reproduced that this is causing the incorrect product codes so I will be working on that.

**Closed** 2023-07-28 22:11 UTC
Labels: bug, help wanted
