### ISSUE TITLE
[Bug]: "invalid Zip archive: Could not find central directory end" on Linux

### ISSUE THREAD

**Issue by stevenlele** [russellbanks/Komac#770] opened 2024-08-19 21:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/stevenlele/winget-update/actions/runs/10461236814/job/28969123177

I've tested that it works correctly on Windows.

**Comment by russellbanks** [comment] 2024-08-19 22:37
This *should* be fixed in Komac v2.4.0 as there has been lots of fixes to do with the central directory in the [zip library](https://github.com/zip-rs/zip2) that komac uses.

**Comment by russellbanks** [comment] 2024-08-22 16:08
> Well, with Komac v2.4.0 it even panicked.

Thanks for the quick test @stevenlele. This issue wasn't to do with the zip but occured when fetching an existing pull request. I've released v2.4.1 to address this.

**Comment by Okeanos** [comment] 2024-08-29 19:22
I can confirm that it does not in fact work on macOS:

Using `https://github.com/tamasfe/taplo/releases/download/0.9.3/taplo-full-windows-x86.zip` as an example will yield

```output
Error:
   0: invalid Zip archive: No valid central directory found
```

**Comment by russellbanks** [comment] 2024-08-30 17:05
Could you possibly test a [nightly](https://github.com/russellbanks/Komac/releases/tag/nightly) build, please? I reckon that this is potentially because on unix systems, the end of the file download may be being stored in a buffer and not being fully written before it gets read. For most files this issue wouldn't arise but to read the central directory, you need to read at the end of the file. I've made a commit that ensures that the download has been fully written to disk before proceeding.

**Closed** 2024-08-30 22:20 UTC
Labels: bug, help wanted

**Comment by Okeanos** [comment] 2024-08-30 22:25
I can also confirm that it works on macOS as well using the nightly build.
